//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport5.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patromic { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string MobileNumber { get; set; }
        public string Passport { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<System.DateTime> LastAuthDate { get; set; }
        public Nullable<System.TimeSpan> LastAAuthTime { get; set; }
        public Nullable<int> TypeOfAuth { get; set; }
        public int GenderId { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
        public virtual TypeOfAuth TypeOfAuth1 { get; set; }
    }
}
